import type { Metadata } from "next";
import styles from "./layout.module.css";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <Link href="/">
            <Image
              src="/images/AjouLogo.png"
              width={100}
              height={100}
              alt="AjouLogo"
            />
          </Link>

          <Link className={styles.link} href="/ultra/course">
            코스
          </Link>
          <Link className={styles.link} href="/ultra/organization">
            조직
          </Link>
          <Link className={styles.link} href="/ultra/calendar">
            캘린더
          </Link>
          <Link className={styles.link} href="/ultra/messages">
            메시지
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
